### PR TITLE
Create harbour-zutun-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,
Swedish translation if wanted.
I also added 2 missing strings in ts file. I leave the qml files to you. 

Settings.qml: Line 90
`text: qsTr("Attach project filter to the left of tasklist.")`

TaskEdit.qml: Line39
`title: qsTr("Edit Task")`

### CODE REVIEW

**Comment by fuchsmich** [comment]
Thank you very much!

**Comment by fuchsmich** [comment]
Released v1.4.1-1 with swedish and german translation. Please test it. Thanks.

**Comment by eson57** [comment]
Thanks! Compiled, tested and found okay early this morning acctually, but checking your build, I found another missing translation string. ;)

TaskList.qml: Line 125
`text: "Creation"`

**Comment by fuchsmich** [comment]
It's the first time I'm translating an app.
I guess I will have to check every string and optimize them for translation (e.g. reuse strings with same meaning).
And there are some words which are widely used on computers (like "reload", "file", and so on). Should/How can I make use these systemwide translations?

**Comment by eson57** [comment]
Sorry, but I'm not the right guy to answer questions about programming. I have translated a lot of apps but I have just about started to slowly learning programming.

**Pull request merged**
